# 
# AppScope Website CI Workflow
#
# Create a git tag with the prefix 'web' and then 'git push --tags'
# to kick off the workflow on github.
#
name: Deploy Website
on:
  push:
    tags:
      - 'web*'
jobs:
  website:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Build schema-reference.md"
        run: make docs-generate

      - name: "Website Deploy"
        run: ./website/deploy.sh
